build:
  image: bjodah/scipy-2017-codegen-tutorial
  environment:
    - CONDA_BLD_PATH=/root/conda-bld
    - ANACONDA_TOKEN=$$ANACONDA_TOKEN
  commands:
    - sed -i.bak '$ d' environment.yml
    - conda env create --quiet -f environment.yml
    - sed -i 's/conda-root-py/python3/' notebooks/*.ipynb
    - bin/render_notebooks.sh
    - bin/prepare_deploy.sh
    - mkdir $CONDA_BLD_PATH
    - conda build --python 35 conda-recipe/
    - conda build --python 36 conda-recipe/
    - conda convert -p all --output $CONDA_BLD_PATH $CONDA_BLD_PATH/linux-64/*.tar.bz2
    - cp -r $CONDA_BLD_PATH/linux-* $CONDA_BLD_PATH/win-* $CONDA_BLD_PATH/osx-* deploy/
    - anaconda -t ${ANACONDA_TOKEN} upload --no-progress -u sympy --force $CONDA_BLD_PATH/*/*.tar.bz2

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: scipy-2017-codegen-tutorial
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
